D-TALE

In [1]:
!pip install dtale

Requirement already satisfied: dtale in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.20.0)
Requirement already satisfied: lz4 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (4.4.5)
Requirement already satisfied: beautifulsoup4!=4.13.0b2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (4.14.3)
Requirement already satisfied: certifi in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2026.1.4)
Requirement already satisfied: cycler in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (0.12.1)
Requirement already satisfied: dash<=2.18.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2.18.2)
Requirement already satisfied: dash-bootstrap-components<=1.7.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.7.1)
Requirement already satisfied: dash_daq<=0.5.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (0.5.0)
Requirement already satisfied: et_xmlfile in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2.0.0)
Requirement already satisfied: Flask in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (3.0.3)
Requirement already satisfied: Flask-Compress in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.23)
Requirement already satisfied: future>=0.14.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.0.0)
Requirement already satisfied: itsdangerous in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2.2.0)
Requirement already satisfied: kaleido in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.2.0)
Requirement already satisfied: matplotlib in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (3.10.0)
Requirement already satisfied: missingno in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (0.5.2)
Requirement already satisfied: networkx in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (3.6.1)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2.4.2)
Requirement already satisfied: openpyxl!=3.2.0b1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (3.1.5)
Requirement already satisfied: packaging in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (25.0)
Requirement already satisfied: pandas in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2.3.2)
Requirement already satisfied: pkginfo in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.12.1.2)
Requirement already satisfied: plotly in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (6.5.2)
Requirement already satisfied: requests in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2.32.5)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.8.0)
Requirement already satisfied: scipy!=1.12.0rc1,!=1.14.0,!=1.14.0rc1,!=1.14.0rc2,<1.16.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.15.3)
Requirement already satisfied: seaborn in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (0.13.2)
Requirement already satisfied: squarify in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (0.4.4)
Requirement already satisfied: statsmodels in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (0.14.6)
Requirement already satisfied: strsimpy in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (0.2.1)
Requirement already satisfied: six in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (1.17.0)
Requirement already satisfied: werkzeug in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (3.0.6)
Requirement already satisfied: xarray in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2026.2.0)
Requirement already satisfied: xlrd in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dtale) (2.0.2)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from beautifulsoup4!=4.13.0b2->dtale) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from beautifulsoup4!=4.13.0b2->dtale) (4.15.0)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash<=2.18.2->dtale) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash<=2.18.2->dtale) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash<=2.18.2->dtale) (5.0.0)
Requirement already satisfied: importlib-metadata in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash<=2.18.2->dtale) (8.7.1)
Requirement already satisfied: retrying in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash<=2.18.2->dtale) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash<=2.18.2->dtale) (1.6.0)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\lib\site-packages (from dash<=2.18.2->dtale) (65.5.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask->dtale) (3.1.6)
Requirement already satisfied: click>=8.1.3 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask->dtale) (8.3.1)
Requirement already satisfied: blinker>=1.6.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask->dtale) (1.9.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly->dtale) (2.16.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from werkzeug->dtale) (2.1.5)
Requirement already satisfied: brotli in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask-Compress->dtale) (1.2.0)
Requirement already satisfied: backports.zstd in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask-Compress->dtale) (1.3.0)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaleido->dtale) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaleido->dtale) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaleido->dtale) (3.11.7)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from kaleido->dtale) (2.4.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->dtale) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->dtale) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->dtale) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->dtale) (12.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->dtale) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib->dtale) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas->dtale) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas->dtale) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dtale) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dtale) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dtale) (2.6.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn->dtale) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scikit-learn->dtale) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from statsmodels->dtale) (1.0.2)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from choreographer>=1.1.1->kaleido->dtale) (3.20.2)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from click>=8.1.3->Flask->dtale) (0.4.6)
Requirement already satisfied: pytest>=7.0.0 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest-timeout>=2.4.0->kaleido->dtale) (9.0.2)
Requirement already satisfied: zipp>=3.20 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from importlib-metadata->dash<=2.18.2->dtale) (3.23.0)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\hp\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (2.19.2)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\hp\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import seaborn as sns

Yes Aanand 👍 that’s correct — and what you did is totally normal.
Let me explain how that works behind the scenes.

✅ What happens when you run:
import seaborn as sns
sns.get_dataset_names()

👉 Seaborn shows a list of sample datasets stored online in its repository.

These are built-in demo datasets for practice and learning.

Examples:

tips

iris

titanic

flights

penguins

✅ When you load a dataset like this:
df = sns.load_dataset("tips")

You feel like you didn’t download anything — but actually:

👉 Seaborn automatically downloads it from the internet
👉 Stores it temporarily
👉 Loads it into a Pandas DataFrame

So technically:
✔ Download hota hai
✔ But automatically (background me)
✔ Tumhe manual download nahi karna padta

✅ Why seaborn provides these datasets

They are for:

✔ Practice EDA
✔ Learning visualization
✔ Teaching machine learning
✔ Quick examples

Matlab ready-made practice data.

✅ Where do these datasets come from?

They are hosted online here:
👉 Seaborn GitHub dataset repository

Python internet se fetch karta hai jab tum load_dataset() run karte ho.

❗ Important limitation

Internet required.

Agar internet off ho → dataset load nahi hoga.

In [3]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']

In [4]:
df=sns.load_dataset('planets')

In [5]:
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [6]:
import dtale

In [9]:
dtale.show(df,open_browser=True)

In [12]:
# DISCLAIMER: 'df' refers to the data you passed in when calling 'dtale.show'

import pandas as pd

if isinstance(df, (pd.DatetimeIndex, pd.MultiIndex)):
	df = df.to_frame(index=False)

# remove any pre-existing indices for ease of use in the D-Tale code, but this is not required
df = df.reset_index().drop('index', axis=1, errors='ignore')
df.columns = [str(c) for c in df.columns]  # update columns to strings in case they are numbers

# main statistics
stats = df['method'].describe().to_frame().T
uniq_vals = df['method'].value_counts().sort_values(ascending=False)
uniq_vals.index.name = 'value'
uniq_vals.name = 'count'
uniq_vals = uniq_vals.reset_index()
uniq_vals.loc[:, 'type'] = 'string'
s = df['method']
s = s[~s.isnull()].str
char_len = s.len()

def calc_len(x):
	try:
		return len(x)
	except:
		return 0

word_len = s.replace(r'[\s]+', ' ').str.split(' ').apply(calc_len)

def txt_count(r):
	return s.count(r).astype(bool).sum()

char_min=char_len.min()
char_max = char_len.max()
char_mean = char_len.mean()
char_std = char_len.std()
with_space = txt_count(r'\s')
with_accent = txt_count(r'[À-ÖÙ-öù-ÿĀ-žḀ-ỿ]')
with_num = txt_count(r'[\d]')
with_upper = txt_count(r'[A-Z]')
with_lower = txt_count(r'[a-z]')
with_punc = txt_count(
		r'(\!|"|\#|\$|%|&|\'|\(|\)|\*|\+|,|\-|\.|/|\:|\;|\<|\=|\>|\?|@|\[|\\|\]|\^|_|\`|\{|\||\}|\~)'
)
space_at_the_first = txt_count(r'^ ')
space_at_the_end = txt_count(r' $')
multi_space_after_each_other = txt_count(r'\s{2,}')
printable = r'''\w \!"#\$%&'\(\)\*\+,\-\./:;<»«؛،ـ\=>\?@\[\\\]\^_\`\{\|\}~'''
with_hidden = txt_count(r'[^{}]+'.format(printable))
word_min = word_len.min()
word_max = word_len.max()
word_mean = word_len.mean()
word_std = word_len.std()

In [13]:
stats

       count unique              top freq
method  1035     10  Radial Velocity  553

2026-02-26 10:14:13,462 - ERROR    - Exception occurred while processing request: list index out of range
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dtale\views.py", line 121, in _handle_exceptions
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dtale\views.py", line 3899, in chart_export_all
    output = export_chart(data_id, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dtale\dash_application\charts.py", line 4158, in export_chart
    chart[0],
    ~~~~~^^^
IndexError: list index out of range
2026-02-26 10:14:26,940 - ERROR    - Exception occurred while processing request: list index out of range
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dtale\views.py", line 121, in _handle_exceptions
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dtale\views.py", line 3899, in chart_export_all
    output = export_chart(data_id, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dtale\dash_application\charts.py", line 4158, in export_chart
    chart[0],
    ~~~~~^^^
IndexError: list index out of range
2026-02-26 11:31:25,310 - INFO     - Executing shutdown due to inactivity...
2026-02-26 11:31:37,534 - INFO     - Executing shutdown...
2026-02-26 11:31:37,535 - INFO     - Not running with the Werkzeug Server, exiting by searching gc for BaseWSGIServer